# Generated by Django 2.2.6 on 2019-10-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='chair',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='specialty',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Degree'),
            preserve_default=False,
        ),
    ]
