# Generated by Django 2.2.6 on 2019-10-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0004_auto_20191031_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
