# Generated by Django 2.2.6 on 2019-11-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0006_remove_specialization_specialization_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialty_code',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_degree', models.CharField(max_length=100)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Chair')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Subject')),
            ],
        ),
    ]
