# Generated by Django 2.2.6 on 2019-11-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0010_auto_20191105_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='individualworkapp.Subject'),
        ),
    ]
