# Generated by Django 2.2.6 on 2019-11-21 21:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0011_auto_20191105_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.CharField(max_length=2000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
