# Generated by Django 2.2.6 on 2019-11-22 08:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0012_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='citizenship',
            field=django_countries.fields.CountryField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
