# Generated by Django 2.2.6 on 2019-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0014_auto_20191122_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='language',
            field=models.ManyToManyField(to='individualworkapp.Language'),
        ),
    ]
