# Generated by Django 2.2.6 on 2019-11-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0015_auto_20191122_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('ed_year', models.CharField(max_length=4)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Degree')),
                ('specialization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Specialization')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birth_year', models.IntegerField()),
                ('score', models.IntegerField()),
                ('gpa', models.IntegerField()),
                ('course', models.CharField(max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Group')),
            ],
        ),
    ]
