# Generated by Django 2.2.6 on 2019-11-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0016_group_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CGroup',
        ),
    ]
