# Generated by Django 2.2.6 on 2019-11-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0017_auto_20191126_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgroup',
            name='ed_year',
            field=models.CharField(max_length=9),
        ),
    ]
