# Generated by Django 2.2.6 on 2019-11-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0018_auto_20191126_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgroup',
            name='specialization',
        ),
    ]
