# Generated by Django 2.2.6 on 2019-11-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0019_remove_cgroup_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgroup',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Specialization'),
        ),
    ]
