# Generated by Django 2.2.6 on 2019-11-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualworkapp', '0021_auto_20191126_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='individualworkapp.Specialty'),
            preserve_default=False,
        ),
    ]
